# Generated by Django 3.2.16 on 2022-11-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homePageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverImg', models.ImageField(upload_to='home_page')),
                ('email', models.CharField(max_length=255)),
                ('linkedIn', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
